# fly.toml app configuration file generated for gemini-web-to-api on 2026-05-11T10:50:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gemini-web-to-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 4981
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
